Repository SMUNION/SMUNION-BE, pull requests merged in 2025-02, with the labels that each got.

#46 ✨ feat: 동아리, 갤러리 S3를 이용하여 이미지 연결
  src/main/java/com/project/smunionbe/domain/club/controller/ClubController.java
  src/main/java/com/project/smunionbe/domain/club/controller/GalleryController.java
  src/main/java/com/project/smunionbe/domain/club/converter/ClubConverter.java
  src/main/java/com/project/smunionbe/domain/club/converter/GalleryConverter.java
  src/main/java/com/project/smunionbe/domain/club/converter/GalleryImagesConverter.java
  src/main/java/com/project/smunionbe/domain/club/dto/request/ClubReqDTO.java
  src/main/java/com/project/smunionbe/domain/club/dto/request/GalleryReqDTO.java
  src/main/java/com/project/smunionbe/domain/club/dto/response/GalleryResDTO.java
  src/main/java/com/project/smunionbe/domain/club/entity/Gallery.java
  src/main/java/com/project/smunionbe/domain/club/repository/GalleryImagesRepository.java
  src/main/java/com/project/smunionbe/domain/club/service/command/ClubCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/command/GalleryCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/ClubQueryService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/GalleryQueryService.java
Labels: ✨feature

#49 ✨ feat: 전체공지 조회 API, 동아리 탈퇴 API 추가
  src/main/java/com/project/smunionbe/domain/club/controller/ClubController.java
  src/main/java/com/project/smunionbe/domain/club/dto/response/ClubResDTO.java
  src/main/java/com/project/smunionbe/domain/club/exception/ClubErrorCode.java
  src/main/java/com/project/smunionbe/domain/club/service/command/ClubCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/ClubQueryService.java
  src/main/java/com/project/smunionbe/domain/member/entity/MemberClub.java
  src/main/java/com/project/smunionbe/domain/notification/basic/repository/BasicNoticeRepository.java
Labels: ✨feature

#50 ♻️ refactor: security, 게시글 코드 refactor
  src/main/java/com/project/smunionbe/domain/community/converter/ArticleConverter.java
  src/main/java/com/project/smunionbe/domain/community/dto/request/ArticleRequestDTO.java
  src/main/java/com/project/smunionbe/domain/community/dto/response/ArticleResponseDTO.java
  src/main/java/com/project/smunionbe/domain/community/entity/Article.java
  src/main/java/com/project/smunionbe/domain/community/service/ArticleService.java
  src/main/java/com/project/smunionbe/domain/member/controller/MemberClubController.java
  src/main/java/com/project/smunionbe/domain/member/exception/AuthErrorCode.java
  src/main/java/com/project/smunionbe/global/config/jwt/TokenAuthenticationFilter.java
Labels: ♻️refactor

#52 ✨feat: 출석 공지 생성 시 설정한 date에 맞게 5분 카운트 난수 생성 & 출석 체크 로직 변경 & 난수 조회 API 개발
  src/main/java/com/project/smunionbe/domain/notification/attendance/controller/AttendanceController.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/dto/request/AttendanceReqDTO.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/exception/AttendanceErrorCode.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/repository/AttendanceStatusRepository.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/command/AttendanceCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/query/AttendanceQueryService.java
  src/main/java/com/project/smunionbe/global/config/TaskSchedulerConfig.java
Labels: ✨feature, ♻️refactor

#54 ♻️ refactor: 부서 중복 처리
  src/main/java/com/project/smunionbe/domain/club/repository/DepartmentRepository.java
  src/main/java/com/project/smunionbe/domain/club/service/command/DepartmentCommandService.java
Labels: ♻️refactor

#61 ♻️ refactor: 모든 동아리 조회에서 동아리 이미지 url도 반환
  src/main/java/com/project/smunionbe/domain/member/converter/MemberClubConverter.java
  src/main/java/com/project/smunionbe/domain/member/dto/response/MemberClubResponseDTO.java
Labels: ♻️refactor
