Repository SMUNION/SMUNION-BE, pull requests merged in 2025-01, with the labels that each got.

#8 ✨feat: 이메일 인증 기능 구현 (#7)
  build.gradle
  src/main/java/com/project/smunionbe/domain/email/controller/EmailAuthController.java
  src/main/java/com/project/smunionbe/domain/email/dto/request/EmailReqDTO.java
  src/main/java/com/project/smunionbe/domain/email/service/DefaultEmailSender.java
  src/main/java/com/project/smunionbe/domain/email/service/EmailAuthService.java
  src/main/java/com/project/smunionbe/domain/member/repository/MemberRepository.java
  src/main/java/com/project/smunionbe/global/config/EmailConfig.java
  src/main/java/com/project/smunionbe/global/config/RedisConfig.java
  src/main/java/com/project/smunionbe/global/config/SecurityConfig.java
  src/main/java/com/project/smunionbe/global/util/RedisUtil.java
  src/main/resources/templates/EmailAuthCodeTemplate.html
Labels: ✨feature

#10 ✨ feat: FCM 토큰 저장 및 푸시 알림 기능 구현 #9
  src/main/java/com/project/smunionbe/domain/notification/attendance/converter/AttendanceConverter.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/command/AttendanceCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/event/FCMNotificationService.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/controller/FCMController.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/converter/FCMConverter.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/dto/request/FCMReqDTO.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/exception/FCMErrorCode.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/exception/FCMException.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/service/command/FCMService.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/service/command/FCMTokenService.java
  src/main/java/com/project/smunionbe/global/config/FirebaseConfig.java
Labels: ✨feature

#17 ✨feat: 출석 공지 API와 memberId 연결
  src/main/java/com/project/smunionbe/domain/notification/attendance/controller/AttendanceController.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/controller/FCMController.java
  src/main/java/com/project/smunionbe/global/config/SecurityConfig.java
  src/main/java/com/project/smunionbe/global/config/jwt/TokenProvider.java
Labels: ✨feature, 🐛fix

#22 ♻️refactor: memberClubId와 출석 공지 API 연결, 미출석 인원조회 API 코드 리팩토링
  src/main/java/com/project/smunionbe/domain/member/repository/MemberRepository.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/controller/AttendanceController.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/dto/request/AttendanceReqDTO.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/command/AttendanceCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/query/AttendanceQueryService.java
Labels: ♻️refactor

#23 ✨ feat: 선택된 MemberClubId 초기 값 지정 및 Redis에서 세션 관리
  build.gradle
  src/main/java/com/project/smunionbe/domain/member/converter/MemberClubConverter.java
  src/main/java/com/project/smunionbe/domain/member/repository/MemberClubRepository.java
  src/main/java/com/project/smunionbe/domain/member/service/ClubSelectionService.java
  src/main/java/com/project/smunionbe/global/config/RedisConfig.java
Labels: ✨feature

#33 ✨feat: 회비 공지 API
  src/main/java/com/project/smunionbe/domain/notification/attendance/dto/request/AttendanceReqDTO.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/dto/response/AttendanceResDTO.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/entity/AttendanceNotice.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/exception/AttendanceErrorCode.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/repository/AttendanceStatusRepository.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/command/AttendanceCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/attendance/service/query/AttendanceQueryService.java
  src/main/java/com/project/smunionbe/domain/notification/fcm/service/event/FCMNotificationService.java
  src/main/java/com/project/smunionbe/domain/notification/fee/controller/FeeController.java
  src/main/java/com/project/smunionbe/domain/notification/fee/converter/FeeNoticeConverter.java
  src/main/java/com/project/smunionbe/domain/notification/fee/dto/request/FeeReqDTO.java
  src/main/java/com/project/smunionbe/domain/notification/fee/dto/response/FeeResDTO.java
  src/main/java/com/project/smunionbe/domain/notification/fee/entity/FeeNotice.java
  src/main/java/com/project/smunionbe/domain/notification/fee/entity/FeeStatus.java
  src/main/java/com/project/smunionbe/domain/notification/fee/exception/FeeErrorCode.java
  src/main/java/com/project/smunionbe/domain/notification/fee/exception/FeeException.java
  src/main/java/com/project/smunionbe/domain/notification/fee/repository/FeeNoticeRepository.java
  src/main/java/com/project/smunionbe/domain/notification/fee/repository/FeeStatusRepository.java
  src/main/java/com/project/smunionbe/domain/notification/fee/service/command/FeeCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/fee/service/query/FeeQueryService.java
  src/main/java/com/project/smunionbe/domain/notification/vote/dto/response/VoteResDTO.java
  src/main/java/com/project/smunionbe/domain/notification/vote/service/command/VoteCommandService.java
  src/main/java/com/project/smunionbe/domain/notification/vote/service/query/VoteQueryService.java
Labels: ✨feature, ♻️refactor

#34 ♻️ refactor: memberId 대신 memberClubId 연결
  src/main/java/com/project/smunionbe/domain/club/controller/ClubController.java
  src/main/java/com/project/smunionbe/domain/club/controller/DepartmentController.java
  src/main/java/com/project/smunionbe/domain/club/controller/GalleryController.java
  src/main/java/com/project/smunionbe/domain/club/dto/request/DepartmentReqDTO.java
  src/main/java/com/project/smunionbe/domain/club/service/command/ClubCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/command/DepartmentCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/command/GalleryCommandService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/ClubQueryService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/DepartmentQueryService.java
  src/main/java/com/project/smunionbe/domain/club/service/query/GalleryQueryService.java
Labels: ♻️refactor

#40 ✨ feat: 회원 추가 기능 구현 #37
  src/main/java/com/project/smunionbe/domain/member/controller/MemberClubController.java
  src/main/java/com/project/smunionbe/domain/member/controller/MemberController.java
  src/main/java/com/project/smunionbe/domain/member/converter/MemberConverter.java
  src/main/java/com/project/smunionbe/domain/member/dto/request/MemberClubRequestDTO.java
  src/main/java/com/project/smunionbe/domain/member/dto/request/MemberRequestDTO.java
  src/main/java/com/project/smunionbe/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/project/smunionbe/domain/member/entity/Member.java
  src/main/java/com/project/smunionbe/domain/member/entity/MemberClub.java
  src/main/java/com/project/smunionbe/domain/member/entity/RefreshToken.java
  src/main/java/com/project/smunionbe/domain/member/exception/AuthErrorCode.java
  src/main/java/com/project/smunionbe/domain/member/exception/MemberClubErrorCode.java
  src/main/java/com/project/smunionbe/domain/member/repository/MemberClubRepository.java
  src/main/java/com/project/smunionbe/domain/member/repository/MemberRepository.java
  src/main/java/com/project/smunionbe/domain/member/security/CustomUserDetails.java
  src/main/java/com/project/smunionbe/domain/member/service/MemberClubService.java
  src/main/java/com/project/smunionbe/domain/member/service/MemberService.java
  src/main/java/com/project/smunionbe/domain/member/service/TokenService.java
  src/main/java/com/project/smunionbe/global/config/SecurityConfig.java
  src/main/java/com/project/smunionbe/global/config/jwt/TokenAuthenticationFilter.java
  src/main/java/com/project/smunionbe/global/config/jwt/TokenProvider.java
Labels: ✨feature

#42 ✨ feat: aws s3를 이용하여 이미지 연결(커뮤니티 / 프로필)
  build.gradle
  src/main/java/com/project/smunionbe/domain/community/controller/ArticleController.java
  src/main/java/com/project/smunionbe/domain/community/converter/ArticleConverter.java
  src/main/java/com/project/smunionbe/domain/community/converter/ArticleImagesConverter.java
  src/main/java/com/project/smunionbe/domain/community/dto/response/ArticleResponseDTO.java
  src/main/java/com/project/smunionbe/domain/community/exception/ImageUploadErrorCode.java
  src/main/java/com/project/smunionbe/domain/community/exception/ImageUploadException.java
  src/main/java/com/project/smunionbe/domain/community/repository/ArticleImagesRepository.java
  src/main/java/com/project/smunionbe/domain/community/service/ArticleService.java
  src/main/java/com/project/smunionbe/domain/community/service/ImageService.java
  src/main/java/com/project/smunionbe/domain/member/controller/MemberController.java
  src/main/java/com/project/smunionbe/domain/member/converter/MemberConverter.java
  src/main/java/com/project/smunionbe/domain/member/dto/response/MemberResponseDTO.java
  src/main/java/com/project/smunionbe/domain/member/entity/Member.java
  src/main/java/com/project/smunionbe/domain/member/exception/MemberErrorCode.java
  src/main/java/com/project/smunionbe/domain/member/service/MemberService.java
  src/main/java/com/project/smunionbe/global/config/S3Config.java
Labels: ✨feature
